-- **JOIN**

-- 조건에 맞는 도서와 저자 리스트 출력하기 (LEVEL 2)
SELECT BOOK_ID, AUTHOR_NAME, TO_CHAR(PUBLISHED_DATE, 'YYYY-MM-DD') AS PUBLISHED_DATE
FROM BOOK
JOIN AUTHOR USING (AUTHOR_ID)
WHERE CATEGORY = '경제'
ORDER BY 3;


-- 상품 별 오프라인 매출 구하기 (LEVEL 2)
SELECT PRODUCT_CODE, SUM(PRICE * SALES_AMOUNT) AS SALES
FROM PRODUCT
JOIN OFFLINE_SALE USING (PRODUCT_ID)
GROUP BY PRODUCT_CODE
ORDER BY 2 DESC, 1;