-- **IS NULL**


-- 경기도에 위치한 식품창고 목록 출력하기 (LEVEL 1)
SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, NVL(FREEZER_YN, 'N') AS FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE WAREHOUSE_NAME LIKE ('%@_경기%') ESCAPE '@'
-- WHERE ADDRESS LIKE ('경기도%')
ORDER BY 1;


-- 이름이 없는 동물의 아이디 ( LEVEL 1 )
SELECT ANIMAL_ID
FROM ANIMAL_INS
WHERE NAME IS NULL
ORDER BY 1;


-- 이름이 있는 동물의 아이디 (LEVEL 1)
SELECT ANIMAL_ID
FROM ANIMAL_INS
WHERE NAME IS NOT NULL
ORDER BY 1;


-- 나이 정보가 없는 회원 수 구하기 (LEVEL 1)
SELECT COUNT(*) AS USERS
FROM USER_INFO
WHERE AGE IS NULL;


-- NULL 처리하기 (LEVEL 2)
SELECT ANIMAL_TYPE, NVL(NAME, 'No name') AS NAME, SEX_UPON_INTAKE
FROM ANIMAL_INS
ORDER BY ANIMAL_ID