-- **GROUP BY**


-- 동명 동물 수 찾기
SELECT NAME, COUNT(NAME) AS "COUNT"
FROM ANIMAL_INS
WHERE NAME IS NOT NULL
GROUP BY NAME
HAVING COUNT(NAME) > 1
ORDER BY 1;


-- 고양이와 개는 몇 마리 있을까
SELECT ANIMAL_TYPE, COUNT(ANIMAL_TYPE) AS "COUNT"
FROM ANIMAL_INS
GROUP BY ANIMAL_TYPE
ORDER BY 1;


-- 고양이와 개는 몇 마리 있을까
SELECT ANIMAL_TYPE, COUNT(ANIMAL_TYPE) AS "COUNT"
FROM ANIMAL_INS
WHERE REGEXP_LIKE(ANIMAL_TYPE, 'Cat|Dog')
GROUP BY ANIMAL_TYPE
ORDER BY 1;


-- 진료과별 총 예약 횟수 출력하기
SELECT MCDP_CD AS "진료과코드", COUNT(MCDP_CD) AS "5월예약건수"
FROM APPOINTMENT
WHERE TO_CHAR(APNT_YMD, 'MM') = '05'
GROUP BY MCDP_CD
ORDER BY 2, 1;


-- 자동차 종류 별 특정 옵션이 포함된 자동차 수 구하기
SELECT CAR_TYPE, COUNT(*) AS "CARS"
FROM CAR_RENTAL_COMPANY_CAR
WHERE OPTIONS LIKE '%시트%'
GROUP BY CAR_TYPE
ORDER BY 1;


-- 가격대 별 상품 개수 구하기
SELECT TRUNC(PRICE, -4) AS "PRICE_GROUP", COUNT(PRODUCT_ID) AS "PRODUCTS"
FROM PRODUCT
GROUP BY TRUNC(PRICE, -4)
ORDER BY 1;


-- 성분으로 구분한 아이스크림 총 주문량
SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS "TOTAL_ORDER"
FROM FIRST_HALF
JOIN ICECREAM_INFO USING (FLAVOR)
GROUP BY INGREDIENT_TYPE
ORDER BY 2;


-- 입양 시각 구하기(1)
SELECT TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) AS "HOUR", COUNT(ANIMAL_ID) AS "COUNT"
FROM ANIMAL_OUTS
GROUP BY TO_NUMBER(TO_CHAR(DATETIME, 'HH24'))
HAVING TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) BETWEEN 9 AND 19
ORDER BY 1;


-- 입양 시각 구하기(2)
SELECT A.HOUR, COUNT(B.HOUR) AS "COUNT"
FROM (SELECT LEVEL - 1 AS HOUR FROM DUAL CONNECT BY LEVEL < 25) A
LEFT JOIN (SELECT TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) AS "HOUR" FROM ANIMAL_OUTS) B ON (A.HOUR = B.HOUR)
GROUP BY A.HOUR
ORDER BY 1;


-- 즐겨찾기가 가장 많은 식당 정보 출력하기
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE (FOOD_TYPE, FAVORITES) 
IN (SELECT FOOD_TYPE, MAX(FAVORITES)
    FROM REST_INFO
    GROUP BY FOOD_TYPE)
ORDER BY 1 DESC;


-- 즐겨찾기가 가장 많은 식당 정보 출력하기
SELECT B.FOOD_TYPE, B.REST_ID, B.REST_NAME, B.FAVORITES
FROM (SELECT FOOD_TYPE, MAX(FAVORITES) FAVORITES
      FROM REST_INFO
      GROUP BY FOOD_TYPE) A, REST_INFO B
WHERE A.FOOD_TYPE = B.FOOD_TYPE
AND A.FAVORITES = B.FAVORITES
ORDER BY 1 DESC;


-- 즐겨찾기가 가장 많은 식당 정보 출력하기 (GPT)
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM (SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES, ROW_NUMBER() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS rnk
      FROM REST_INFO)
WHERE rnk = 1
ORDER BY 1 DESC;
